### PR TITLE
fix(secgroup): crud compatibility based on the ver.1

### LINKED ISSUE #2048: [VPC] The ver.3 API does not supported in ap-southeast-2
Hi team,

In ap-southeast-2, I cannot use `huaweicloud_networking_secgroup` because version 3 API is not released.

Best regards!

### PR DESCRIPTION
**Pull request by Lance52259**
**What this PR does / why we need it**:
- The ver.3 API of Security Group and Security Group Rule are not supported at some regions.
- A parameter description has Computed behavior that will cause updates to not apply to this parameter.

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #2048 

**Special notes for your reviewer**:

**Release note**:

```release-note
1. add ver.1 and ver.2 sdks to support the create and get methods after ver.3 method failed.
2. remove the computed behavior.
```

## PR Checklist

* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

```
NONE
```

### CODE REVIEW

File: huaweicloud/resource_huaweicloud_networking_secgroup.go [hunk 1]
```diff
@@ -174,41 +233,77 @@ func resourceNetworkingSecGroupCreate(ctx context.Context, d *schema.ResourceDat
 
 func resourceNetworkingSecGroupRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
 	config := meta.(*config.Config)
-	client, err := config.NetworkingV3Client(GetRegion(d, config))
+	region := GetRegion(d, config)
+	v1Client, err := config.SecurityGroupV1Client(region)
+	if err != nil {
+		return fmtp.DiagErrorf("Error creating HuaweiCloud networking v1 client: %s", err)
```
Comment (hmbig2) [inline huaweicloud/resource_huaweicloud_networking_secgroup.go:222]: it is security group cilent

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go [hunk 2]
```diff
@@ -53,48 +56,110 @@ func DataSourceNetworkingSecGroup() *schema.Resource {
...
+	rules, err := flattenV1SecurityGroupRules(resp)
+	if err != nil {
+		return diag.FromErr(err)
+	}
+	mErr := multierror.Append(nil,
+		d.Set("region", region),
+		d.Set("name", resp.Name),
+		d.Set("description", resp.Description),
+		d.Set("enterprise_project_id", resp.EnterpriseProjectId),
+		d.Set("rules", rules),
```
Comment (hmbig2) [inline huaweicloud/data_source_huaweicloud_networking_secgroup.go]: the setting fields are different between v3 and v1

File: huaweicloud/resource_huaweicloud_networking_secgroup.go (hunk 1 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_networking_secgroup.go:222]: The difference between SecurityGroupV1Client() and NetworkingV1Client() is just whether there is a projectId in the URL.
They are all networking clients.

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go (hunk 2 above)
Comment (Lance52259) [reply huaweicloud/data_source_huaweicloud_networking_secgroup.go]: In the ver.1 response, the structure does not have `created_at` and `updated_at`, but it has `enterprise_project_id`, this parameter that was missing in the old code's settings.

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go [hunk 3]
```diff
@@ -53,51 +57,129 @@ func DataSourceNetworkingSecGroup() *schema.Resource {
...
-		Name: d.Get("name").(string),
-	}
-	if epsId := common.GetEnterpriseProjectID(d, config); epsId != "" {
-		listOpts.EnterpriseProjectId = epsId
-	} else {
-		listOpts.EnterpriseProjectId = "all_granted_eps"
+	listOpts := v3Groups.ListOpts{
+		ID:                  d.Get("secgroup_id").(string),
+		Name:                d.Get("name").(string),
+		EnterpriseProjectId: config.DataGetEnterpriseProjectID(d),
```
Comment (niuzhenguo) [inline huaweicloud/data_source_huaweicloud_networking_secgroup.go:81]: suggest to keep "all_granted_eps" here.

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go [hunk 4]
```diff
@@ -53,51 +57,129 @@ func DataSourceNetworkingSecGroup() *schema.Resource {
...
 	}
 
-	allSecGroups, err := groups.List(networkingClient, listOpts)
+	allSecGroups, err := v3Groups.List(v3Client, listOpts)
 	if err != nil {
+		if _, ok := err.(golangsdk.ErrDefault404); ok {
+			// If the v3 API does not exist or has not been published in the specified region, try to set using v1 API.
+			return setV1SecurityGroupDetail(d, config, region)
```
Comment (niuzhenguo) [inline huaweicloud/data_source_huaweicloud_networking_secgroup.go]: I would suggest name this func like `dataSourceNetworkingSecGroupReadV1` and combine `dataSourceNetworkingSecGroupRead` with `getSecurityGroupByV1Client` to make it like a common `Read` function as we have.

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go [hunk 5]
```diff
@@ -53,51 +57,129 @@ func DataSourceNetworkingSecGroup() *schema.Resource {
 	}
 }
 
+func getSecurityGroupByV1Client(d *schema.ResourceData, config *config.Config) (*v1Groups.SecurityGroup, error) {
```
Comment (niuzhenguo) [inline huaweicloud/data_source_huaweicloud_networking_secgroup.go]: have you already checked whether V1 API is availalbe on the regions that V3 not available, like ap-southest-2, G42 regions? if not, better to use v2 API.

File: huaweicloud/resource_huaweicloud_networking_secgroup.go [hunk 6]
```diff
@@ -124,47 +126,104 @@ func ResourceNetworkingSecGroup() *schema.Resource {
...
 		Name:                d.Get("name").(string),
 		EnterpriseProjectId: GetEnterpriseProjectID(d, config),
 	}
 
 	logp.Printf("[DEBUG] Create HuaweiCloud Security Group: %#v", createOpts)
-	securityGroup, err := groups.Create(client, createOpts)
+	securityGroup, err := v3Groups.Create(v3Client, createOpts)
 	if err != nil {
+		if _, ok := err.(golangsdk.ErrDefault404); ok {
+			err = createSecurityGroupByV1Client(d, config)
```
Comment (niuzhenguo) [inline huaweicloud/resource_huaweicloud_networking_secgroup.go]: ditto. I would suggest name it to `resourceNetworkingSecGroupCreateV1` as a common Create function and return resourceNetworkingSecGroupReadV1 directly inside.

File: huaweicloud/resource_huaweicloud_networking_secgroup.go [hunk 7]
```diff
@@ -249,23 +345,35 @@ func flattenSecurityGroupRules(secGroup *groups.SecurityGroup) ([]map[string]int
...
+	_, err = v3Groups.Update(client, d.Id(), updateOpts)
+	if err != nil {
+		if _, ok := err.(golangsdk.ErrDefault404); ok {
+			v2Client, err := config.NetworkingV2Client(region)
+			if err != nil {
+				return fmtp.DiagErrorf("Error creating HuaweiCloud networking v2 client: %s", err)
+			}
+
+			// The v1 API does not support creating and updating description parameters.
+			err = updateSecurityGroupByV2Client(d, v2Client)
```
Comment (niuzhenguo) [inline huaweicloud/resource_huaweicloud_networking_secgroup.go]: ditto

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go [hunk 8]
```diff
@@ -83,13 +94,13 @@ func getSecGroupDetail(secGroup groups.SecurityGroup) map[string]interface{} {
...
-func filterAvailableSecGroups(d *schema.ResourceData, secGroups []groups.SecurityGroup) ([]map[string]interface{},
+func filterAvailableV1SecGroups(d *schema.ResourceData, secGroups []v1Groups.SecurityGroup) ([]map[string]interface{},
 	[]string) {
 	secGroupCopy := secGroups
 
 	// build filter by description content.
 	if desc, ok := d.GetOk("description"); ok {
-		tmp := make([]groups.SecurityGroup, 0, len(secGroupCopy))
+		tmp := make([]v1Groups.SecurityGroup, 0, len(secGroupCopy))
 		for _, secgroup := range secGroupCopy {
```
Comment (Jason-Zhang9309) [inline huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: why name is not support in this filter?

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go [hunk 9]
```diff
@@ -72,7 +74,16 @@ func DataSourceNetworkingSecGroups() *schema.Resource {
 	}
 }
 
-func getSecGroupDetail(secGroup groups.SecurityGroup) map[string]interface{} {
+func flattenV1SecGroupDetail(secGroup v1Groups.SecurityGroup) map[string]interface{} {
```
Comment (Jason-Zhang9309) [inline huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: please consider merge flattenV1SecGroupDetail and flattenV3SecGroupDetail into one func

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go (hunk 3 above)
Comment (Lance52259) [reply huaweicloud/data_source_huaweicloud_networking_secgroup.go:81]: The DataGetEnterpriseProjectID method will return `all_granted_eps` when epsId is empty.

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go (hunk 4 above)
Comment (Lance52259) [reply huaweicloud/data_source_huaweicloud_networking_secgroup.go:154]: `ap-southest-2` region has been checked.

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go (hunk 5 above)
Comment (Lance52259) [reply huaweicloud/data_source_huaweicloud_networking_secgroup.go]: `ap-southest-2` region has been checked.

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go [hunk 10]
```diff
@@ -83,13 +94,13 @@ func getSecGroupDetail(secGroup groups.SecurityGroup) map[string]interface{} {
 	}
 }
 
-func filterAvailableSecGroups(d *schema.ResourceData, secGroups []groups.SecurityGroup) ([]map[string]interface{},
+func filterAvailableV1SecGroups(d *schema.ResourceData, secGroups []v1Groups.SecurityGroup) ([]map[string]interface{},
```
Comment (Jason-Zhang9309) [inline huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: please consider merge filterAvailableV1SecGroups and filterAvailableV3SecGroups into one func

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go [hunk 11]
```diff
@@ -103,40 +114,94 @@ func filterAvailableSecGroups(d *schema.ResourceData, secGroups []groups.Securit
...
+	ids := make([]string, len(tmp))
+	for i, secGroup := range tmp {
+		ids[i] = secGroup.ID
+		result[i] = flattenV3SecGroupDetail(secGroup)
 	}
 
 	return result, ids
 }
 
 func dataSourceNetworkingSecGroupsRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
```
Comment (Jason-Zhang9309) [inline huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go:153]: please use capitalized func name for future reference in other provider

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go (hunk 5 above)
Comment (Jason-Zhang9309) [reply huaweicloud/data_source_huaweicloud_networking_secgroup.go]: V2 API is Openstack API which not support EPS Authorization

File: huaweicloud/resource_huaweicloud_networking_secgroup_rule.go [hunk 12]
```diff
@@ -123,122 +120,138 @@ func ResourceNetworkingSecGroupRule() *schema.Resource {
...
-	}
 
-	return nil
-}
-
-func setSecurityGroupRulePorts(d *schema.ResourceData, portRange string) error {
-	if portRange == "" {
-		return nil
+	rule, err := v3Rules.Get(v3Client, d.Id())
+	if _, ok := err.(golangsdk.ErrDefault404); ok {
```
Comment (Jason-Zhang9309) [inline huaweicloud/resource_huaweicloud_networking_secgroup_rule.go]: what if the error is not 404?

File: huaweicloud/resource_huaweicloud_networking_secgroup.go [hunk 13]
```diff
@@ -174,43 +233,79 @@ func resourceNetworkingSecGroupCreate(ctx context.Context, d *schema.ResourceDat
...
 		d.Set("rules", secGroupRule),
-		d.Set("created_at", securityGroup.CreatedAt),
-		d.Set("updated_at", securityGroup.UpdatedAt),
 	)
-	if mErr.ErrorOrNil() != nil {
-		return diag.FromErr(mErr)
+
+	// If the ver.3 API is supported, setting related parameters.
+	v3Resp, err := v3Groups.Get(v3Client, d.Id())
+	if _, ok := err.(golangsdk.ErrDefault404); ok {
```
Comment (Jason-Zhang9309) [inline huaweicloud/resource_huaweicloud_networking_secgroup.go]: what if the error is not 404?

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go [hunk 14]
```diff
@@ -53,51 +57,129 @@ func DataSourceNetworkingSecGroup() *schema.Resource {
...
+	listOpts := v3Groups.ListOpts{
+		ID:                  d.Get("secgroup_id").(string),
+		Name:                d.Get("name").(string),
+		EnterpriseProjectId: config.DataGetEnterpriseProjectID(d),
 	}
 
-	allSecGroups, err := groups.List(networkingClient, listOpts)
+	allSecGroups, err := v3Groups.List(v3Client, listOpts)
 	if err != nil {
+		if _, ok := err.(golangsdk.ErrDefault404); ok {
```
Comment (Jason-Zhang9309) [inline huaweicloud/data_source_huaweicloud_networking_secgroup.go:86]: is there a more accurate way to determine whether the V3 API is available？
error code 404 can be found in many situations

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go (hunk 4 above)
Comment (Lance52259) [reply huaweicloud/data_source_huaweicloud_networking_secgroup.go]: done.

File: huaweicloud/resource_huaweicloud_networking_secgroup.go (hunk 6 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_networking_secgroup.go]: done.

File: huaweicloud/resource_huaweicloud_networking_secgroup.go (hunk 7 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_networking_secgroup.go]: done.

File: huaweicloud/resource_huaweicloud_networking_secgroup_rule.go (hunk 12 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_networking_secgroup_rule.go]: Since the V1 version of the query was previously performed, if the resource does not exist, the function process will not reach this step, so only the situation where the API does not exist is left.

File: huaweicloud/resource_huaweicloud_networking_secgroup.go (hunk 13 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_networking_secgroup.go]: ditto.

File: huaweicloud/data_source_huaweicloud_networking_secgroup.go (hunk 14 above)
Comment (Lance52259) [reply huaweicloud/data_source_huaweicloud_networking_secgroup.go:86]: In either case, the 404 will be verified using the API of the V1 version.

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go (hunk 8 above)
Comment (Lance52259) [reply huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: fixed.

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go (hunk 9 above)
Comment (Lance52259) [reply huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: The current codes is clearer.
Not adopted

Comment (Lance52259) [reply huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: done.

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go (hunk 10 above)
Comment (Lance52259) [reply huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: The current codes is clearer.
Not adopted

File: huaweicloud/resource_huaweicloud_networking_secgroup.go [hunk 15]
```diff
@@ -124,93 +126,169 @@ func ResourceNetworkingSecGroup() *schema.Resource {
...
-	securityGroup, err := groups.Get(client, d.Id())
+	v1Resp, err := v1groups.Get(v1Client, d.Id()).Extract()
 	if err != nil {
 		return common.CheckDeletedDiag(d, err, "HuaweiCloud Security group")
 	}
 
-	logp.Printf("[DEBUG] Retrieved Security Group %s: %+v", d.Id(), securityGroup)
-
-	secGroupRule, err := flattenSecurityGroupRules(securityGroup)
+	logp.Printf("[DEBUG] Retrieved Security Group (%s) by v3 client: %v", d.Id(), v1Resp)
```
Comment (ShiChangkuo) [inline huaweicloud/resource_huaweicloud_networking_secgroup.go]: s/v3/v1/

File: huaweicloud/resource_huaweicloud_networking_secgroup.go [hunk 16]
```diff
@@ -124,93 +126,169 @@ func ResourceNetworkingSecGroup() *schema.Resource {
...
+		mErr = multierror.Append(mErr,
+			d.Set("rules", rules), // Override the configuration of the rules list.
+			d.Set("created_at", v3Resp.CreatedAt),
+			d.Set("updated_at", v3Resp.UpdatedAt),
+		)
 	}
 
-	return nil
+	// If the query process returns an error, either because the specified region does not exist or the v3 API is
+	// not released, or other reasons, skip the setting.
```
Comment (ShiChangkuo) [inline huaweicloud/resource_huaweicloud_networking_secgroup.go:266]: seems the comments are extra

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go [hunk 17]
```diff
@@ -72,71 +77,150 @@ func DataSourceNetworkingSecGroups() *schema.Resource {
...
+	return result
+}
+
+func filterAvailableSecGroupsV1(d *schema.ResourceData, secGroups []v1groups.SecurityGroup) ([]map[string]interface{},
+	[]string) {
+	tmp := make([]v1groups.SecurityGroup, 0, len(secGroups))
+
+	// Build filter by name and description content.
+	for _, secgroup := range secGroups {
+		if name, ok := d.GetOk("name"); ok {
```
Comment (ShiChangkuo) [inline huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: suggest to put d.GetOk outside the loop

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go [hunk 18]
```diff
@@ -72,71 +77,150 @@ func DataSourceNetworkingSecGroups() *schema.Resource {
...
+			if name != secgroup.Name {
+				continue
+			}
+		}
+		if desc, ok := d.GetOk("description"); ok {
+			if !strings.Contains(secgroup.Description, desc.(string)) {
```
Comment (ShiChangkuo) [inline huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: we shoud make a filtering rule about `description` field

File: huaweicloud/resource_huaweicloud_networking_secgroup.go (hunk 16 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_networking_secgroup.go:266]: This comment is used to explain what the code does if error is not `nil`.

File: huaweicloud/resource_huaweicloud_networking_secgroup.go (hunk 15 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_networking_secgroup.go]: done.

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go (hunk 17 above)
Comment (Lance52259) [reply huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: done.

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go [hunk 19]
```diff
@@ -72,71 +77,157 @@ func DataSourceNetworkingSecGroups() *schema.Resource {
...
-		"name":                  secGroup.Name,
-		"enterprise_project_id": secGroup.EnterpriseProjectId,
-		"description":           secGroup.Description,
-		"created_at":            secGroup.CreatedAt,
-		"updated_at":            secGroup.UpdatedAt,
+func flattenSecGroupDetail(secGroup interface{}) map[string]interface{} {
+	var result map[string]interface{}
+	switch secGroup.(type) {
+	case v1Group:
+		entity := secGroup.(v1Group)
```
Comment (hmbig2) [inline huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: s/switch secGroup.(type)/switch secGroup=secGroup.(type)

**Comment by Lance52259** [comment]
```
make testacc TEST='./huaweicloud/services/acceptance/vpc' TESTARGS='-run=TestAccNetworkingSecGroupsDataSource_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/vpc -v -run=TestAccNetworkingSecGroupsDataSource_basic -timeout 360m -parallel 4
=== RUN   TestAccNetworkingSecGroupsDataSource_basic
=== PAUSE TestAccNetworkingSecGroupsDataSource_basic
=== CONT  TestAccNetworkingSecGroupsDataSource_basic
--- PASS: TestAccNetworkingSecGroupsDataSource_basic (53.71s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/vpc       54.362s
```
```
make testacc TEST='./huaweicloud/services/acceptance/vpc' TESTARGS='-run=TestAccNetworkingSecGroupsDataSource_description'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/vpc -v -run=TestAccNetworkingSecGroupsDataSource_description -timeout 360m -parallel 4
=== RUN   TestAccNetworkingSecGroupsDataSource_description
=== PAUSE TestAccNetworkingSecGroupsDataSource_description
=== CONT  TestAccNetworkingSecGroupsDataSource_description
--- PASS: TestAccNetworkingSecGroupsDataSource_description (51.26s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/vpc       51.676s
```

File: huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go (hunk 19 above)
Comment (Lance52259) [reply huaweicloud/services/vpc/data_source_huaweicloud_networking_secgroups.go]: done.
