### PR TITLE
fix(dms/kafka): fix the force replacement problem

### LINKED ISSUE #2009: [Kafka] The forces replacement problem about availability zone list
Hi team,

When I using `huaweicloud_dms_kafka_instance` to manage Kafka, it is found that the order of elements in the AZ list is different, and `forces replacement` will appear after the creation is complete.
```
# huaweicloud_dms_kafka_instance.default must be replaced
-/+ resource "huaweicloud_dms_kafka_instance" "default" {
      ~ availability_zones         = [ # forces replacement
            "cn-north-4a",
          - "cn-north-4c",
            "cn-north-4b",
          + "cn-north-4c",
        ]
```

Best regards!

### PR DESCRIPTION
**Pull request by Lance52259**
**What this PR does / why we need it**:
Fix terraform resource re-creation due to wrong order of the availability zone list return from Kafka API.

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #2009 

**Special notes for your reviewer**:

**Release note**:

```release-note
1. update AZ schema type from TypeList to TypeSet.
```

## PR Checklist

* [ ] Tests added/passed.
* [ ] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

```
NONE
```

### CODE REVIEW

**Comment by niuzhenguo** [comment]
dms/rabbitmq instance has the same problems, pls fix them together.

File: huaweicloud/services/dms/resource_huaweicloud_dms_kafka_instance.go [hunk 1]
```diff
@@ -84,11 +84,13 @@ func ResourceDmsKafkaInstance() *schema.Resource {
 				ForceNew: true,
 			},
 			"availability_zones": {
-				Type:     schema.TypeList,
+				// There is a problem with order of elements in Availability Zone list returned by Kafka API.
+				Type:     schema.TypeSet,
```
Comment (niuzhenguo) [inline huaweicloud/services/dms/resource_huaweicloud_dms_kafka_instance.go:88]: just a question: do we need to update the type to Set on docs. I just find we only have one `Set` type filed on `compute_servergroup`, not sure if it's needed.

Comment (Lance52259) [reply huaweicloud/services/dms/resource_huaweicloud_dms_kafka_instance.go:88]: This question is actually about whether the user refers to this field, because the processing of the two types of Set and List is different.
For the breaking change declear,  we need to make it clear.
```
~> The parameter behavior of `availability_zones` has been changed from `TypeList` to `TypeSet`.
```
