### PR TITLE
fix(evs/attach): add error parsing for delete check function

### LINKED ISSUE #2194: [EVS] The CheckDeleted method is not right
Hi team,

I found an error when I refresh my script.

How I found out:
Step 1: create an instance and a volume and attach the volume to the instance.
Step 2: untach the volume in the console.
Step 3: refresh the script.

```
Error: error fetching compute_volume_attach: Bad request with: [GET https://ecs.cn-north-4.myhuaweicloud.com/v1/0970dd7a1300f5672ff2c003c60ae115/cloudservers/f9b0f31c-a742-4053-9958-9921f94efd3f/block_device/bf70bd77-38dd-4db3-b473-31db1afc4733], error message: {"error":{"message":"{\"itemNotFound\": {\"message\": \"No volume Block Device Mapping with id bf70bd77-38dd-4db3-b473-31db1afc4733.\", \"code\": 404}}","code":"Ecs.1000"}}
│ 
│   with huaweicloud_compute_volume_attach.flash_ecs1_attachments[0],
│   on main.tf line 239, in resource "huaweicloud_compute_volume_attach" "flash_ecs1_attachments":
│  239: resource "huaweicloud_compute_volume_attach" "flash_ecs1_attachments" {
```

### PR DESCRIPTION
**Pull request by Lance52259**
**What this PR does / why we need it**:
Add a function to parsing 404 not found error.
Since the ECS API response is 400, we should support a function to parse and translate it into a 404 error.

For FunctionGraph API response, the status code is 500, and the error content is:
```
Error: error retrieving FunctionGraph trigger: Internal Server Error: [GET [https://functiongraph.cn-north-4.myhuaweicloud.com/v2/0970dd7a1300f5672ff2c003c60ae115/fgs/triggers/urn:fss:cn-north-4:0970dd7a1300f5672ff2c003c60ae115:function:default:script_fgs_triggers_function]](https://functiongraph.cn-north-4.myhuaweicloud.com/v2/0970dd7a1300f5672ff2c003c60ae115/fgs/triggers/urn:fss:cn-north-4:0970dd7a1300f5672ff2c003c60ae115:function:default:script_fgs_triggers_function%5D), error message: {
│ "error_code": "FSS.0500",
│ "error_msg": "Error getting associated function"
│ }
```

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #2194 

**Special notes for your reviewer**:

**Release note**:

```release-note
1. support a new error parsing function.
```

## PR Checklist

* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

```
 Warning: Resource not found
│ 
│   with huaweicloud_compute_volume_attach.flash_ecs1_attachments[0],
│   on main.tf line 239, in resource "huaweicloud_compute_volume_attach" "flash_ecs1_attachments":
│  239: resource "huaweicloud_compute_volume_attach" "flash_ecs1_attachments" {
│ 
│ the resource edfeee55-748f-4d44-98de-5b2b657b2e0d/a21bc4a2-57c9-4f02-b995-1baeee583dea is
│ gone and will be removed in Terraform state.
│ 
│ (and one more similar warning elsewhere)
```

### CODE REVIEW

File: huaweicloud/services/fgs/resource_huaweicloud_fgs_trigger.go [hunk 1]
```diff
@@ -830,3 +837,18 @@ func resourceFunctionGraphTriggerDelete(d *schema.ResourceData, meta interface{}
 	d.SetId("")
 	return nil
 }
+
+func parseRequestError(respErr error) error {
+	var apiErr trigger.Error
+	if errCode, ok := respErr.(golangsdk.ErrDefault500); ok && errCode.Body != nil {
+		pErr := json.Unmarshal(errCode.Body, &apiErr)
+		if pErr == nil && apiErr.Code == "FSS.0500" && apiErr.Message == "Error getting associated function" {
```
Comment (hmbig2) [inline huaweicloud/services/fgs/resource_huaweicloud_fgs_trigger.go:845]: pls remove `apiErr.Message == "Error getting associated function"`, message maybe change.

Comment (Lance52259) [reply huaweicloud/services/fgs/resource_huaweicloud_fgs_trigger.go:845]: The errors of FSS.0500 code is not only `function not found`.
