### PR TITLE
feat(cce/node_attach): fix the error when attaching a prePaid ECS

### LINKED ISSUE #2395: [CCE] Node attach failed when attaching a prePaid instance
Error messages below reported when I attach a prePaid ECS instance into CCE:
```
2022-09-22T20:09:07.651+0800 [DEBUG] provider.terraform-provider-huaweicloud_v1.40.1: API Response Code: 200: timestamp=2022-09-22T20:09:07.651+0800
2022-09-22T20:09:07.651+0800 [DEBUG] provider.terraform-provider-huaweicloud_v1.40.1: API Response Headers:
Cache-Control: no-cache, no-store, must-revalidate
Cache-Control: no-cache, no-store, must-revalidate
Connection: keep-alive
Content-Type: application/json
Date: Thu, 22 Sep 2022 12:09:07 GMT
Pragma: no-cache
Pragma: no-cache
Server: api-gateway
Set-Cookie: ingress-cfe-cluster-manager-6443=279b515f9e09a03bda2bb83619ba07ab; Path=/; Secure; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubdomains;
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Request-Id: 27624219d67fddd2f9f95d8feb25abc3
X-Xss-Protection: 1; mode=block;: timestamp=2022-09-22T20:09:07.651+0800
2022-09-22T20:09:07.652+0800 [DEBUG] provider.terraform-provider-huaweicloud_v1.40.1: API Response Body: {
  "apiVersion": "v3",
  "kind": "Node",
  "metadata": {
    "annotations": {
      "kubernetes.io/node-pool.id": "DefaultPool",
      "os.architecture": "amd64"
    },
    "creationTimestamp": "2022-09-22 12:05:47.336298 +0000 UTC",
    "name": "test",
    "uid": "xxxxxx-xxxxx-xxxx-xxxxx-xxxxxxxxxx",
    "updateTimestamp": "2022-09-22 12:08:42.705957 +0000 UTC"
  },
  "spec": {
    "az": "cn-east-3c",
    "billingMode": 1,
    "dataVolumes": [
      {
        "hw:passthrough": true,
        "metadata": {
          "__system__server_id": "xxxxxx-xxxxx-xxxx-xxxxx-xxxxxxxxxx",
          "attached_mode": "rw",
          "hw:passthrough": "true",
          "orderID": "CSXXXXXXXXXXXXXXX",
          "productID": "xxxxx-xxxxxx-x--x",
          "readonly": "False"
        },
        "size": 100,
        "volumetype": "SAS"
      }
    ],
    "ecsGroupId": "xxxxxx-xxxxx-xxxx-xxxxx-xxxxxxxxxx",
    "extendParam": {
      "chargingMode": 1,
      "orderID": "",
      "productID": ""
    },
    "flavor": "c7.2xlarge.4",
    "isStatic": true,
    "login": {
      "sshKey": "xxxxx",
      "userPassword": {}
    },
    "nodeNicSpec": {
      "primaryNic": {
        "subnetId": "xxxxxx-xxxxx-xxxx-xxxxx-xxxxxxxxxx"
      }
    },
    "os": "EulerOS 2.5",
    "publicIP": {
      "eip": {
        "bandwidth": {}
      }
    },
    "rootVolume": {
      "hw:passthrough": true,
      "metadata": {
        "__system__server_id": "xxxxxx-xxxxx-xxxx-xxxxx-xxxxxxxxxx",
        "attached_mode": "rw",
        "billing": "1",
        "hw:passthrough": "true",
        "orderID": "CSXXXXXXXXXXXXXXX",
        "productID": "xxxxx-xxxxxx-x--x",
        "readonly": "False"
      },
      "size": 40,
      "volumetype": "SAS"
    },
    "runtime": {
      "name": "docker"
    }
  },
  "status": {
    "phase": "Active",
    "privateIP": "xxx.xxx.xxx.xxx",
    "serverId": "xxxxxx-xxxxx-xxxx-xxxxx-xxxxxxxxxx"
  }
}: timestamp=2022-09-22T20:09:07.652+0800
2022-09-22T20:09:07.654+0800 [ERROR] provider.terraform-provider-huaweicloud_v1.40.1: setting state: Invalid address to set: []string{"charging_mode"}: timestamp=2022-09-22T20:09:07.654+0800
```

### PR DESCRIPTION
**Pull request by Jason-Zhang9309**
**What this PR does / why we need it**:

fix the error when attaching a prePaid ECS

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #2395 

**Special notes for your reviewer**:

**Release note**:

```release-note
fix the error when attaching a prePaid ECS
```

## PR Checklist

* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

```
make testacc TEST='./huaweicloud/services/acceptance/cce' TESTARGS='-run TestAccCCENodeAttachV3_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/cce -v -run TestAccCCENodeAttachV3_basic -timeout 360m -parallel 4
=== RUN   TestAccCCENodeAttachV3_basic
=== PAUSE TestAccCCENodeAttachV3_basic
=== CONT  TestAccCCENodeAttachV3_basic
--- PASS: TestAccCCENodeAttachV3_basic (1196.83s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/cce       1196.905s

make testacc TEST='./huaweicloud/services/acceptance/cce' TESTARGS='-run TestAccCCENodeAttachV3_prePaid'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/cce -v -run TestAccCCENodeAttachV3_prePaid -timeout 360m -parallel 4
=== RUN   TestAccCCENodeAttachV3_prePaid
=== PAUSE TestAccCCENodeAttachV3_prePaid
=== CONT  TestAccCCENodeAttachV3_prePaid
--- PASS: TestAccCCENodeAttachV3_prePaid (947.77s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/cce       947.860s
```

### CODE REVIEW

File: huaweicloud/services/acceptance/cce/resource_huaweicloud_cce_node_attach_test.go [hunk 1]
```diff
@@ -58,6 +58,34 @@ func TestAccCCENodeAttachV3_basic(t *testing.T) {
...
+func TestAccCCENodeAttachV3_prePaid(t *testing.T) {
+	var node nodes.Nodes
+
+	rName := fmt.Sprintf("tf-acc-test-%s", acctest.RandString(5))
+	resourceName := "huaweicloud_cce_node_attach.test"
+	//clusterName here is used to provide the cluster id to fetch cce node.
+	clusterName := "huaweicloud_cce_cluster.test"
+
+	resource.ParallelTest(t, resource.TestCase{
+		PreCheck:          func() { acceptance.TestAccPreCheck(t) },
```
Comment (ShiChangkuo) [inline huaweicloud/services/acceptance/cce/resource_huaweicloud_cce_node_attach_test.go]: please add `TestAccPreCheckChargingMode` precheck

Comment (Jason-Zhang9309) [reply huaweicloud/services/acceptance/cce/resource_huaweicloud_cce_node_attach_test.go]: fixed
