### PR TITLE
fix(elb): release eip when deleting the ELB loadbalancer

### LINKED ISSUE #1893: [ELB] eip will not be released  with elb loadbalancer
If you create elb loadbalancer with eip, the eip will not be automatically release when you destroying the loadbalancer.

### PR DESCRIPTION
**Pull request by ShiChangkuo**
**What this PR does / why we need it**:

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #1893 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

## PR Checklist

* [x] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

```
$ make testacc TEST='./huaweicloud/services/acceptance/elb' TESTARGS='-run TestAccElbV3LoadBalancer_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/elb -v -run TestAccElbV3LoadBalancer_basic -timeout 360m -parallel 4
=== RUN   TestAccElbV3LoadBalancer_basic
=== PAUSE TestAccElbV3LoadBalancer_basic
=== CONT  TestAccElbV3LoadBalancer_basic
--- PASS: TestAccElbV3LoadBalancer_basic (83.56s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/elb       83.623s

$ make testacc TEST='./huaweicloud/services/acceptance/elb' TESTARGS='-run TestAccElbV3LoadBalancer_withEIP'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/elb -v -run TestAccElbV3LoadBalancer_withEIP -timeout 360m -parallel 4
=== RUN   TestAccElbV3LoadBalancer_withEIP
=== PAUSE TestAccElbV3LoadBalancer_withEIP
=== CONT  TestAccElbV3LoadBalancer_withEIP
--- PASS: TestAccElbV3LoadBalancer_withEIP (49.07s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/elb       49.131s
```

### CODE REVIEW

File: huaweicloud/services/elb/resource_huaweicloud_elb_loadbalancer.go [hunk 1]
```diff
@@ -437,7 +440,34 @@ func resourceLoadBalancerV3Delete(ctx context.Context, d *schema.ResourceData, m
...
+		eipClient, err := config.NetworkingV1Client(region)
+		if err == nil {
+			if eipErr := eips.Delete(eipClient, eipID).ExtractErr(); eipErr != nil {
+				if _, ok := err.(golangsdk.ErrDefault404); !ok {
+					eipDiag := diag.Diagnostic{
+						Severity: diag.Warning,
+						Summary:  "failed to delete EIP",
+						Detail:   fmt.Sprintf("failed to delete EIP %s: %s", eipID, eipErr),
+					}
+					diags = append(diags, eipDiag)
```
Comment (hmbig2) [inline huaweicloud/services/elb/resource_huaweicloud_elb_loadbalancer.go:457]: without any other errors append to, why not just return

Comment (ShiChangkuo) [reply huaweicloud/services/elb/resource_huaweicloud_elb_loadbalancer.go:457]: we can seems this scenario be success with a warning message
