### PR TITLE
fix(security group): Add new validation of the protocol type setting

### LINKED ISSUE #1749: [VPC] The security group protocol is not set correctly
Hi team,
    When the user configures the security group rule of the `any` protocol in the script, the re-creation logic will be triggered due to the `ForceNew` attribute.
    Because of the security group protocol `any` is null in the API response, and provider is missing related logic to deal with it.

### PR DESCRIPTION
**Pull request by Lance52259**
**What this PR does / why we need it**
The resource failed to properly set any type of security group policy.
When the security group rule was created, the protocol was set to "any", but the protocol value was not stored correctly in the state. As a result, changes occurred:
  - `null` -> `any`

For about API response, only protocol values (None, 'tcp', 'udp', 'icmp', 'icmpv6') and integer representations (0 to 255) are supported. So, add a new validation for protocol.
Any one of them is verified as true means that the protocol is filled in correctly:
- Whether the protocol is one of `udp`, `tcp`, `icmp` and `icmpv6`.
- Whether the protocol is range from 0 to 255.
- If omitted, protocol means `any` (will not be set).

**Which issue this PR fixes**:
fixes #1749

**Special notes for your reviewer**:

**Release note**:

```release-note
1. Add new validation of the protocol type setting.
```

## PR Checklist

* [ ] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

```
make testacc TEST='./huaweicloud' TESTARGS='-run=TestAccNetworkingV2SecGroupRule'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud -v -run=TestAccNetworkingV2SecGroupRule -timeout 360m -parallel 4
=== RUN   TestAccNetworkingV2SecGroupRule_basic
=== PAUSE TestAccNetworkingV2SecGroupRule_basic
=== RUN   TestAccNetworkingV2SecGroupRule_remoteGroup
=== PAUSE TestAccNetworkingV2SecGroupRule_remoteGroup
=== RUN   TestAccNetworkingV2SecGroupRule_lowerCaseCIDR
=== PAUSE TestAccNetworkingV2SecGroupRule_lowerCaseCIDR
=== RUN   TestAccNetworkingV2SecGroupRule_numericProtocol
=== PAUSE TestAccNetworkingV2SecGroupRule_numericProtocol
=== CONT  TestAccNetworkingV2SecGroupRule_basic
=== CONT  TestAccNetworkingV2SecGroupRule_numericProtocol
=== CONT  TestAccNetworkingV2SecGroupRule_lowerCaseCIDR
=== CONT  TestAccNetworkingV2SecGroupRule_remoteGroup
--- PASS: TestAccNetworkingV2SecGroupRule_lowerCaseCIDR (103.36s)
--- PASS: TestAccNetworkingV2SecGroupRule_remoteGroup (115.01s)
--- PASS: TestAccNetworkingV2SecGroupRule_basic (115.36s)
--- PASS: TestAccNetworkingV2SecGroupRule_numericProtocol (115.42s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       115.526s
```

### CODE REVIEW

File: huaweicloud/resource_huaweicloud_networking_secgroup_rule_v2.go [hunk 1]
```diff
@@ -181,18 +181,25 @@ func resourceNetworkingSecGroupRuleV2Read(d *schema.ResourceData, meta interface
...
 	d.Set("remote_ip_prefix", security_group_rule.RemoteIPPrefix)
 	d.Set("security_group_id", security_group_rule.SecGroupID)
 	d.Set("tenant_id", security_group_rule.TenantID)
 	d.Set("region", GetRegion(d, config))
+	setSecurityGroupRuleProtocol(d, security_group_rule.Protocol)
 
 	return nil
 }
 
+func setSecurityGroupRuleProtocol(d *schema.ResourceData, protocol string) error {
```
Comment (ShiChangkuo) [inline huaweicloud/resource_huaweicloud_networking_secgroup_rule_v2.go]: suggest to return to the processed protocol and set it in the Read function.

Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_networking_secgroup_rule_v2.go]: The forced type conversion has been used.
