### PR TITLE
fix: add elb autoscaling

### LINKED ISSUE #1339: [ELB] Add autoscaling support
I'd like to add autoscaling support for ELB v3.

### LINKED ISSUE #2373: ELB 缺少负载均衡器弹性扩缩容开关
image

image

### PR DESCRIPTION
**Pull request by houpeng80**
**What this PR does / why we need it**:

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #1339 
fixes #2373 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

## PR Checklist

* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

```
make testacc TEST='./huaweicloud' TESTARGS='-run=TestAccSomethingV0_basic'
...
=== RUN   TestAccSomethingV0_basic
--- PASS: TestAccSomethingV0_basic (70.75s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       70.796s
```

### CODE REVIEW

**Comment by Lance52259** [comment]
missing document modification

File: huaweicloud/services/elb/resource_huaweicloud_elb_loadbalancer.go [hunk 1]
```diff
@@ -200,6 +200,16 @@ func ResourceLoadBalancerV3() *schema.Resource {
...
+			"enable": {
+				Type:     schema.TypeBool,
+				Optional: true,
+				Computed: true,
+			},
+			"min_l7_flavor_id": {
+				Type:     schema.TypeString,
+				Optional: true,
+				Computed: true,
+			},
```
Comment (Lance52259) [inline huaweicloud/services/elb/resource_huaweicloud_elb_loadbalancer.go]: required with `l7_flavor_id`?
```
Specifies the ID of the minimum Layer-7 flavor for elastic scaling. This parameter cannot be left blank if there are HTTP or HTTPS listeners.
```

Comment (houpeng80) [reply huaweicloud/services/elb/resource_huaweicloud_elb_loadbalancer.go]: done

File: docs/resources/elb_loadbalancer.md [hunk 2]
```diff
@@ -156,6 +156,12 @@ The following arguments are supported:
 * `auto_renew` - (Optional, String, ForceNew) Specifies whether auto renew is enabled. Valid values are **true** and
   **false**. Changing this parameter will create a new resource.
 
+* `enable` - (Optional, Bool) Specifies whether autoscaling is enabled. Valid values are **true** and
```
Comment (ShiChangkuo) [inline docs/resources/elb_loadbalancer.md]: suggest to rename it to **autoscaling_enabled**

File: docs/resources/elb_loadbalancer.md [hunk 3]
```diff
@@ -156,6 +156,12 @@ The following arguments are supported:
...
+  **false**.
+
+* `min_l7_flavor_id` - (Optional, String) The L7 flavor min id. The type is L7_Elastic. It can not be empty when the
```
Comment (ShiChangkuo) [inline docs/resources/elb_loadbalancer.md]: please update the description from API docs

File: huaweicloud/services/elb/resource_huaweicloud_elb_loadbalancer.go [hunk 4]
```diff
@@ -438,6 +460,22 @@ func resourceLoadBalancerV3Update(ctx context.Context, d *schema.ResourceData, m
...
+				Enable: enable,
+			}
+			if v, ok := d.GetOk("l4_flavor_id"); ok && !enable {
+				updateOpts.L4Flavor = v.(string)
+			}
+			if v, ok := d.GetOk("l7_flavor_id"); ok && !enable {
+				updateOpts.L7Flavor = v.(string)
+			}
+			if v, ok := d.GetOk("min_l7_flavor_id"); ok {
+				updateOpts.AutoScaling.MinL7Flavor = v.(string)
```
Comment (ShiChangkuo) [inline huaweicloud/services/elb/resource_huaweicloud_elb_loadbalancer.go]: we can set the value directly as it will be omitted if empty in SDK.

File: docs/resources/elb_loadbalancer.md (hunk 2 above)
Comment (houpeng80) [reply docs/resources/elb_loadbalancer.md]: done

File: docs/resources/elb_loadbalancer.md (hunk 3 above)
Comment (houpeng80) [reply docs/resources/elb_loadbalancer.md]: done

File: huaweicloud/services/elb/resource_huaweicloud_elb_loadbalancer.go (hunk 4 above)
Comment (houpeng80) [reply huaweicloud/services/elb/resource_huaweicloud_elb_loadbalancer.go]: done

File: docs/resources/elb_loadbalancer.md [hunk 5]
```diff
@@ -155,6 +155,12 @@ The following arguments are supported:
 
 * `auto_renew` - (Optional, String) Specifies whether auto renew is enabled. Valid values are **true** and **false**.
 
+* `autoscaling_enabled` - (Optional, Bool) Specifies whether autoscaling is enabled. Valid values are **true** and
+  **false**.
+
+* `min_l7_flavor_id` - (Optional, String) The min L7 flavor id of ELB. The type is L7_Elastic. It can not be empty when
+  the loadbalancer has a listener of L7.
```
Comment (ShiChangkuo) [inline docs/resources/elb_loadbalancer.md]:
```suggestion
* `min_l7_flavor_id` - (Optional, String) Specifies the ID of the minimum Layer-7 flavor for elastic scaling.
  This parameter cannot be left blank if there are HTTP or HTTPS listeners.
```
this is copied from [API docs](https://support.huaweicloud.com/intl/en-us/api-elb/CreateLoadBalancer.html#CreateLoadBalancer__request_CreateLoadbalancerAutoscalingOption), you can also add more informations about it.

Comment (houpeng80) [reply docs/resources/elb_loadbalancer.md]: done
