### PR TITLE
fix(node pool): redesign the initial node count

### LINKED ISSUE #1757: [CCE] Iinitial number of nodes will be automatically scaled and updated by the autoscaler tool
Hi team,

The initial number of nodes will be updated by the auto-scaling event of the auto-scaling tool.
If we configure the autoscaler tool and some events occur, the `initial_node_count` will be changed and trigger a resource change.
Please help to fix it.

### PR DESCRIPTION
**Pull request by Lance52259**
**What this PR does / why we need it**:
initial_node_count represents both the initial number of nodes and the current number of nodes. The parameters have multiple meanings and do not conform to the design principles.

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #1757

**Special notes for your reviewer**:

**Release note**:

```release-note
1. add a current_node_count parameters to show the current number of nodes.
2. remove the setting of initial_node_count.
```

## PR Checklist

* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

```
make testacc TEST='./huaweicloud' TESTARGS='-run=TestAccCCENodePool_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud -v -run=TestAccCCENodePool_basic -timeout 360m -parallel 4
=== RUN   TestAccCCENodePool_basic
=== PAUSE TestAccCCENodePool_basic
=== CONT  TestAccCCENodePool_basic
--- PASS: TestAccCCENodePool_basic (1233.42s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       1233.522s
```

### CODE REVIEW

File: huaweicloud/resource_huaweicloud_cce_node_pool.go [hunk 1]
```diff
@@ -47,6 +47,11 @@ func ResourceCCENodePool() *schema.Resource {
 				Type:     schema.TypeInt,
 				Required: true,
 			},
+			"expect_node_count": {
```
Comment (niuzhenguo) [inline huaweicloud/resource_huaweicloud_cce_node_pool.go]: seems `expect_node_count` is unneeded.

**Comment by Lance52259** [comment]
```
make testacc TEST='./huaweicloud' TESTARGS='-run=TestAccCCENodePool_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud -v -run=TestAccCCENodePool_basic -timeout 360m -parallel 4
=== RUN   TestAccCCENodePool_basic
=== PAUSE TestAccCCENodePool_basic
=== CONT  TestAccCCENodePool_basic
--- PASS: TestAccCCENodePool_basic (1701.97s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       1702.049s
```

File: huaweicloud/resource_huaweicloud_cce_node_pool.go (hunk 1 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_cce_node_pool.go]: already removed.

File: docs/resources/cce_node_pool.md [hunk 2]
```diff
@@ -50,7 +50,8 @@ The following arguments are supported:
 
 * `name` - (Required, String) Node Pool Name.
 
-* `initial_node_count` - (Required, Int) Initial number of expected nodes in the node pool.
+* `initial_node_count` - (Required, Int) Specifies the initial number of expected nodes in the node pool.
+  This parameter is used to manual scaling and conflicts with auto scaling.
```
Comment (Jason-Zhang9309) [inline docs/resources/cce_node_pool.md]: `conflicts` is confusing. Is there any better way to describe the relationship between this parameter and auto scaling?

Comment (niuzhenguo) [reply docs/resources/cce_node_pool.md]: seems we can get rid of this line, or maybe update to something like `This parameter can be also used to manually scale the node count afterwards`

Comment (Lance52259) [reply docs/resources/cce_node_pool.md]: `This parameter can be also used to manually scale the node count afterwards` is better.
