### PR TITLE
fix(compute/instance): fix CheckDeleted issue

### LINKED ISSUE #1793: [ECS] CheckDeleted doesn't take effect and cause Delete issue
As ecs destroy only set the status to DELETED, CheckDeleted will not take effect.

### PR DESCRIPTION
**Pull request by niuzhenguo**
**What this PR does / why we need it**:

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #1793 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

## PR Checklist

* [x] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

```
make testacc TEST=./huaweicloud/ TESTARGS='-run=TestAccComputeV2Instance'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/ -v -run=TestAccComputeV2Instance -timeout 360m -parallel 4
=== RUN   TestAccComputeV2Instance_basic
=== PAUSE TestAccComputeV2Instance_basic
=== RUN   TestAccComputeV2Instance_disks
=== PAUSE TestAccComputeV2Instance_disks
=== RUN   TestAccComputeV2Instance_prePaid
=== PAUSE TestAccComputeV2Instance_prePaid
=== RUN   TestAccComputeV2Instance_tags
=== PAUSE TestAccComputeV2Instance_tags
=== RUN   TestAccComputeV2Instance_powerAction
=== PAUSE TestAccComputeV2Instance_powerAction
=== CONT  TestAccComputeV2Instance_basic
=== CONT  TestAccComputeV2Instance_tags
=== CONT  TestAccComputeV2Instance_powerAction
=== CONT  TestAccComputeV2Instance_prePaid
--- PASS: TestAccComputeV2Instance_basic (221.01s)
=== CONT  TestAccComputeV2Instance_disks
--- PASS: TestAccComputeV2Instance_prePaid (226.14s)
--- PASS: TestAccComputeV2Instance_disks (215.79s)
--- PASS: TestAccComputeV2Instance_tags (507.42s)
--- PASS: TestAccComputeV2Instance_powerAction (721.37s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       721.398s
```

### CODE REVIEW

File: huaweicloud/resource_huaweicloud_compute_instance_test.go [hunk 1]
```diff
@@ -10,6 +10,7 @@ import (
 
 	"github.com/chnsz/golangsdk/openstack/common/tags"
 	"github.com/chnsz/golangsdk/openstack/compute/v2/servers"
+	"github.com/chnsz/golangsdk/openstack/ecs/v1/cloudservers"
```
Comment (ShiChangkuo) [inline huaweicloud/resource_huaweicloud_compute_instance_test.go]: suggest to replace all v2/servers APIs with v1 APIs in the testing.

Comment (niuzhenguo) [reply huaweicloud/resource_huaweicloud_compute_instance_test.go]: done
