### PR TITLE
Power action parameter and method supported

### LINKED ISSUE #914: PowerOn state for ECS
The state parameter is sorely lacking when managing the ECS.
Will this parameter be added?

### LINKED ISSUE #1044: Add Poweroff/poweron on addition ECS to huaweicloud_compute_servergroup
Hello,

### Terraform Version
Terraform v0.14.8

### Affected Resource(s)
Please list the resources as a list, for example:
- **huaweicloud_compute_instance**
- **huaweicloud_compute_servergroup**

### Actual Behavior
For now ECS is not automatically stopped/started when it's added to huaweicloud_compute_servergroup. This causes errors  such as:

```
Error: Error to add a instance to ECS server group, err=Bad request with: [POST https://....], error message: {"error":{"message":"{\"badRequest\": {\"message\": \"Instance ... can not add, cause its state is not STOPPED\", \"code\": 400}}","code":"Ecs.1000"}}
```

and forces administrator to stop ECSes manually as prerequisite to servergroup operations.

### Expected Behavior
It would be nice to embed this ECS auto-stop/start into servergroup operation process like it's implemented for ECS flavor switching operation.

### PR DESCRIPTION
**Pull request by Lance52259**
**What this PR does / why we need it**:
- Redundancy of the instance status detection method.
- Power action supports:
  - ON
  - OFF
  - REBOOT
  - FORCE-OFF
  - FORCE-REBOOT

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #914
fixes #1044

**Special notes for your reviewer**:

**Release note**:

```release-note
1. Extract the instance status detection method
2. New power state option and method supported.
```

## PR Checklist

* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed
```
make testacc TEST='./huaweicloud' TESTARGS='-run=TestAccComputeV2Instance_powerAction'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud -v -run=TestAccComputeV2Instance_powerAction -timeout 360m -parallel 4
=== RUN   TestAccComputeV2Instance_powerAction
=== PAUSE TestAccComputeV2Instance_powerAction
=== CONT  TestAccComputeV2Instance_powerAction
--- PASS: TestAccComputeV2Instance_powerAction (523.11s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       523.172s
```

### CODE REVIEW

File: huaweicloud/resource_huaweicloud_compute_instance.go [hunk 1]
```diff
@@ -286,6 +295,14 @@ func ResourceComputeInstanceV2() *schema.Resource {
 				ValidateFunc: utils.ValidateECSTagValue,
 				Elem:         &schema.Schema{Type: schema.TypeString},
 			},
+			"power_action": {
+				Type:     schema.TypeString,
+				Optional: true,
+				// If you want to support more actions, please update powerActionMap simultaneously.
+				ValidateFunc: validation.StringInSlice([]string{
+					"ON", "OFF", "REBOOT", "FORCE-OFF", "FORCE-REBOOT",
+				}, true),
```
Comment (ShiChangkuo) [inline huaweicloud/resource_huaweicloud_compute_instance.go]: seems the ignoreCase shoud be `false`.

File: huaweicloud/resource_huaweicloud_compute_instance.go [hunk 2]
```diff
@@ -631,6 +639,17 @@ func resourceComputeInstanceV2Create(d *schema.ResourceData, meta interface{}) e
 		}
 	}
 
+	// Create an instance in the shutdown state.
+	if action, ok := d.GetOk("power_action"); ok {
+		if action.(string) != "OFF" {
```
Comment (ShiChangkuo) [inline huaweicloud/resource_huaweicloud_compute_instance.go]: **FORCE-OFF** should also be valid during the creation.

File: huaweicloud/resource_huaweicloud_compute_instance.go [hunk 3]
```diff
@@ -631,6 +639,17 @@ func resourceComputeInstanceV2Create(d *schema.ResourceData, meta interface{}) e
...
+			log.Printf("[WARN] The power action (%s) is invalid after instance created", action.(string))
+		} else {
+			if err = doPowerAction(ecsClient, d, action.(string)); err != nil {
+				return fmt.Errorf("Unable to close the huaweicloud compute instance (%s): %s", d.Id(), err)
```
Comment (ShiChangkuo) [inline huaweicloud/resource_huaweicloud_compute_instance.go]: the error message shoud be updated.

File: huaweicloud/resource_huaweicloud_compute_instance.go (hunk 1 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_compute_instance.go]: case ignore is set false now

File: huaweicloud/resource_huaweicloud_compute_instance.go (hunk 2 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_compute_instance.go]: thx, the FORCE-OFF has added

File: huaweicloud/resource_huaweicloud_compute_instance.go (hunk 3 above)
Comment (Lance52259) [reply huaweicloud/resource_huaweicloud_compute_instance.go]: The message has updated.

File: docs/resources/compute_instance.md [hunk 4]
```diff
@@ -283,6 +283,10 @@ The following arguments are supported:
 * `agency_name` - (Optional, String, ForceNew) Specifies the IAM agency name which is created on IAM to provide
     temporary credentials for ECS to access cloud services. Changing this creates a new instance.
 
+* `power_action` - (Optional, String) Specifies what action needs to be done for the instance.
```
Comment (ShiChangkuo) [inline docs/resources/compute_instance.md]: Specifies the power action to be done for ...

Comment (Lance52259) [reply docs/resources/compute_instance.md]: The description has updated, and the note info `The power_action is a one-time action.` is better than `The power_action parameter specifies a one-time action.`?
