### PR TITLE
fix(scm): for security, do not print the private key in the log

### LINKED ISSUE #1631: [SCM] For security,  the private key must be shielded when printing log
When importing the SCM certificate, the private key will be printed to the log file, which will leak the certificate and cause security problems.
So, the private key must be shielded when printing log.

### PR DESCRIPTION
**Pull request by chengxiangdong**
**What this PR does / why we need it**:

- For security, the private key must be shielded when printing log.
- Move the code files to service path.

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #1631

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

## PR Checklist

* [x] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

```
make testacc TEST='./huaweicloud/services/acceptance/scm' TESTARGS='-run TestAccScmCertification'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/scm -v -run TestAccScmCertification -timeout 360m -parallel 4
=== RUN   TestAccScmCertification_basic
=== PAUSE TestAccScmCertification_basic
=== RUN   TestAccScmCertification_push
=== PAUSE TestAccScmCertification_push
=== RUN   TestAccScmCertification_batchPush
=== PAUSE TestAccScmCertification_batchPush
=== CONT  TestAccScmCertification_basic
=== CONT  TestAccScmCertification_batchPush
=== CONT  TestAccScmCertification_push
--- PASS: TestAccScmCertification_batchPush (52.03s)
--- PASS: TestAccScmCertification_push (80.61s)
--- PASS: TestAccScmCertification_basic (88.89s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/scm       89.063s

```

### CODE REVIEW

File: huaweicloud/services/scm/resource_huaweicloud_scm_certificate.go [hunk 1]
```diff
@@ -275,30 +281,35 @@ func pushCertificateToService(id string, pushOpts certificates.PushOpts, scmClie
...
-
+	mErr := multierror.Append(nil,
+		d.Set("region", config.GetRegion(d)),
+		d.Set("status", certDetail.Status),
+		d.Set("name", certDetail.Name),
+		d.Set("push_support", certDetail.PushSupport),
+	)
 	// convert the type of 'certDetail.Authentifications' to TypeList
 	auths := buildAuthtificatesAttribute(certDetail.Authentifications)
 	d.Set("authentifications", auths)
```
Comment (hmbig2) [inline huaweicloud/services/scm/resource_huaweicloud_scm_certificate.go]: pls move those to mutierror.append
